### ISSUE TITLE
El valor de la carta "A" esta por debajo de la carta "2"

### ISSUE THREAD

**Issue by kholostyak17** [YifanYes/Sorting-Cards#2]
-La carta A en el poker sería como la equivalente a la carta 1 ;), pues debería verse la primera en cada ordenación:

![image](https://user-images.githubusercontent.com/80543950/129584780-ee668540-9ec5-44cf-81ae-6905f06a55ff.png)

- "Un as es un naipe de la baraja francesa e inglesa, que representan al número 1"
https://es.wikipedia.org/wiki/As_(naipe)

**Comment by YifanYes** [comment]
En el Poker Texas Holdem no jajajajaja es la carta más alta

**Comment by kholostyak17** [comment]
todos los dias se aprende algo nuevo 😮 🎲
